# Generated by Django 2.2.3 on 2019-07-21 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190720_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')])),
                ('user_dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
