# Generated by Django 2.2.3 on 2019-07-21 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190721_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only alphabets are allowed.')]),
        ),
    ]
