# Generated by Django 2.2.3 on 2019-07-21 08:00

from django.db import migrations
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dob',
            field=webapp.models.TodayOrLaterDateField(),
        ),
    ]
