# Generated by Django 2.2.3 on 2019-07-21 09:07

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190721_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dob',
            field=models.DateField(validators=[webapp.models.validate_date_today_or_later]),
        ),
    ]
